### ISSUE TITLE
`samples` does not exist

### ISSUE THREAD

**Issue by ismay** [rochars/wavefile#1]
It seems that `samples` does not exist as documented in the readme:

```
// array of numbers
console.log(wav.samples);
```

instead, it's available under `samples_`, and the unit tests seem to only test for the `samples_` property as well. Is this an oversight? Should samples not be available under `samples` and not `samples_`?

**Comment by rochars** [comment]
"samples_" was renamed to "samples" and "bitDepth_" was renamed to "bitDepth". Thanks.

**Comment by ismay** [comment]
Cool, thanks for the quick fix! 👍🎉
