### ISSUE TITLE
Can I make new WaveFile(...) from browser?

### ISSUE THREAD

**Issue by prostoandrei** [rochars/wavefile#10]
Hello!

I have only a link to file on remote server. How can I make WaveFile from browser?

```
var WaveFile = new WaveFile('./trueWav.wav');
console.log(wav.chunkSize);
```
returns `Uncaught Error: Not a supported format.`

How can I make a buffer from it in browser?

Thank you :)

**Comment by rochars** [comment]
WaveFile currently do not have any method for reading remote files. You should somehow download the file and then use WaveFile to read it.

Thanks!
Rafael
