### ISSUE TITLE
Stereo to Mono and Mono to Stereo

### ISSUE THREAD

**Issue by cdcv** [rochars/wavefile#12]
How can wavefile be used to change this?
This is currently an important topic for speech recognition as data is often recorded as stereo, but needs to be submitted for recognition as mono.

Thanks!

**Comment by rochars** [comment]
The current version of wavefile does not support this. I will add this to the roadmap for a future release. Thanks!

**Comment by itsalb3rt** [comment]
Any notice ?

**Comment by sandcobainer** [comment]
Was this update completed? Although it's not a major roadblock in usage, it would be nice to provide a quick convertToMono function. 

I believe `wav.getSamples()` already provides de-interleaved channel data and averaging the channels is a naive conversion to Mono from multi-channel audio

**Comment by gokaybiz** [comment]
Is there any update?
