### ISSUE TITLE
ES6 import syntax results in TypeError: wavefile_1.default is not a constructor

### ISSUE THREAD

**Issue by zachschultz** [rochars/wavefile#16]
Importing WaveFile like so: `import WaveFile from "wavefile"` and attempting to create an instance like: `const reader = new WaveFile()` results in the following error: `TypeError: wavefile_1.default is not a constructor`.

However, importing like: `const wavefile = require("wavefile")` works fine, but then TypeScript type checking stops working.

**Comment by rochars** [comment]
Use the `--esModuleInterop` flag when using ES6 imports - something like this:

`$ tsc index.ts --esModuleInterop`

Cheers!
Rafael
