### ISSUE TITLE
Recognize End Points for Cue Markers

### ISSUE THREAD

**Issue by craigeley** [rochars/wavefile#17]
This is a feature request or enhancement, but I'm wondering if it is possible for wavefile to recognize cue markers that have both a start AND end point—markers like this can be created in Adobe Audition, for example. Note the "start" and "end" times in this screenshot:

<img width="1321" alt="Screen Shot 2020-01-02 at 3 14 14 PM" src="https://user-images.githubusercontent.com/1425316/71693630-90f94b80-2d72-11ea-9382-f40e7081ff20.png">

And here is a link to the file that the screenshot was taken with:

https://www.dropbox.com/transfer/AAAAACWjc7db0I3xtIeZ8l9CdhEH-kgKOCyCfrkJFS1nwrv-vYQ3Nu8

Would love to know your thoughts on if this is possible.

**Comment by rochars** [comment]
Thanks for the file!

The bug that corrupted files like this is solved in version 9.0.2 - the files can be saved and the regions are kept (they are showing up in Reaper). Some of the values are not displaying correctly, still.

This file uses some features that the current version of wavefile do not support, but im working to add support for them in future releases. I included the file in the test suite. Thanks!

Cheers!
Rafael

**Comment by rochars** [comment]
Version 9.1.1 should handle the regions correctly.

Cheers!
Rafael

**Comment by craigeley** [comment]
Amazing! Read and write?

**Comment by rochars** [comment]
In version 9.x you can only read and write regions that already existed in the file. In v10.x will be possible to use the *setCuePoint* method to create both cue points and regions.

Cheers!

**Comment by rochars** [comment]
Version 10.0 is out; now you can add regions like this:
```javascript
// create a cue region with a label:
wav.setCuePoint({position: 1500, end: 2500, label: 'some label'});
```
To create a standard cue point, ommit the 'end' attribute:
```javascript
// create a cue point with a label:
wav.setCuePoint({position: 1500, label: 'some label'});
// create a cue point with no label:
wav.setCuePoint({position: 1500});
```

Cheers!
Rafael

**Comment by craigeley** [comment]
This is awesome. I have _no idea_ the magic that makes this script work, but I would be interested to know if it can parse files from Pro Tools, which writes "clips" into its files in a way that I have never been able to get another app to read. But that's a different issue for a different day. Thanks again!

**Comment by rochars** [comment]
Could you provide a file with some clips like that?

Cheers!
Rafael
