### ISSUE TITLE
Semver adherence

### ISSUE THREAD

**Issue by ismay** [rochars/wavefile#2]
I think the recent updates didn't have to be major version updates. It seems like there aren't any breaking api changes but just bug fixes and added functionality. So this could have been done with minor and patch versions. See the semver spec for information on what version number to increment when: https://semver.org

It would be nice to also document the releases in something like a changelog: https://keepachangelog.com/en/1.0.0, so people know what changed.

**Comment by ismay** [comment]
Didn't mean this to sound unthankful by the way, I think it's great that this library is so actively maintained 👍

**Comment by rochars** [comment]
Thanks for the feedback. There were some changes that could break the API, but mostly with undocumented properties.
