### ISSUE TITLE
waveFile.toBuffer as 16 bit array?

### ISSUE THREAD

**Issue by marksyzm** [rochars/wavefile#33]
I'm just working on something that generates peaks for wave files which I read the data from via base64, and to match what I have I'd prefer the buffer to output in 16 bit, possibly signed format?

Is there a way to do this with what 

This would be my ideal:
```
const waveFile = new WaveFile();      
waveFile.fromDataURI(waveFileBase64);
const audioFileBuffer = waveFile.toBuffer('16');
```
Or can I just convert this to 16 bit? 

Many thanks

**Comment by kookster** [comment]
Maybe use toBitDepth(16), then output using toBuffer?

**Comment by marksyzm** [comment]
But according to the code, toBuffer only outputs 8-bit?

**Comment by marksyzm** [comment]
Being able to set the buffer size would be ideal, especially to 8, 16, 24, or 32-bit.

**Comment by kookster** [comment]
Yeah toBuffer maybe not; try getSamples(false, Int16Array); ?

**Comment by marksyzm** [comment]
Aha! That sounds like it

**Comment by marksyzm** [comment]
Yes, how did I miss that?? Thank you!

**Comment by marksyzm** [comment]
Also, thank you so much for such amazing work on this. There was barely anything else out there that did all this and you saved me having to work out something from scratch for all this. Brilliant job, thank you!
