### ISSUE TITLE
Writing BWF Bext chunk

### ISSUE THREAD

**Issue by MichaelKlier** [rochars/wavefile#5]
Hi,

first of thanks for creating this <3! I was wondering if it would be possible to add support to write/update the bwf bext chunk of a wav file. I tried changing the values in <fn>.bext but it's not written back to the file. I've checked with bwf meta edit, a tool to edit bwf meta data.

Thanks,
Michael

**Comment by rochars** [comment]
I included this in the roadmap:
https://github.com/rochars/wavefile/blob/master/ROADMAP.md

Thanks!

**Comment by MichaelKlier** [comment]
Awesome! Thanks a lot!! (only gut the notification when you closed the issue :)).
